Import data

In [1]:
import pandas as pd
import numpy as np

from IPython.display import display, HTML

In [2]:
filepath="D:\\GitHub\\eEcoLiDAR\\Annotation\\Data\\"

header=pd.read_csv(filepath+'Phragmites_australis_header.csv',sep='\t')
species=pd.read_csv(filepath+'Phragmites_australis_species.csv',sep='\t')

print(header.dtypes)
print("-----------------")
print(species.dtypes)

PlotObservationID                   int64
PlotID                              int64
Bedekkingsschaal                   object
Datum van opname                   object
Lengte proefvlak (m)              float64
Breedte proefvlak (m)             float64
Opp. proefvlak (m²)               float64
Bedekking totaal (%)              float64
Bedekking boomlaag (%)            float64
Bedekking struiklaag (%)          float64
Bedekking kruidlaag (%)           float64
Bedekking moslaag (%)             float64
Hoogte (hoge) boomlaag (m)        float64
Hoogte lage boomlaag (m)          float64
Hoogte (hoge) struiklaag (m)      float64
Hoogte lage struiklaag (m)        float64
Gem. hoogte (hoge) kruidl (cm)    float64
Gem. hoogte lage kruidl. (cm)     float64
Maximale hoogte kruidlaag (cm)    float64
Associa (1)                        object
Incompleteness (1)                float64
Longitude                         float64
Latitude                          float64
Location uncertainty (m)            int64
Dataset                            object
dtype: object
-----------------
PlotObservationID      int64
Species name          object
Layer                  int64
Cover %              float64
Cover code            object
Taxon ID               int64
dtype: object

In [3]:
year=2005

#print(header["Datum van opname"].str[-4:].astype('float64'))

header_upyear=header[(header["Datum van opname"].str[-4:].astype('float64')>year)]

In [5]:
pd.set_option('display.max_columns', None)
header_upyear.head(n=20)

header_specific=header[(header["PlotObservationID"]==192)]
header_specific

,PlotObservationID,PlotID,Bedekkingsschaal,Datum van opname,Lengte proefvlak (m),Breedte proefvlak (m),Opp. proefvlak (m²),Bedekking totaal (%),Bedekking boomlaag (%),Bedekking struiklaag (%),Bedekking kruidlaag (%),Bedekking moslaag (%),Hoogte (hoge) boomlaag (m),Hoogte lage boomlaag (m),Hoogte (hoge) struiklaag (m),Hoogte lage struiklaag (m),Gem. hoogte (hoge) kruidl (cm),Gem. hoogte lage kruidl. (cm),Maximale hoogte kruidlaag (cm),Associa (1),Incompleteness (1),Longitude,Latitude,Location uncertainty (m),Dataset
0,192,192,"Braun/Blanquet (B,D&S)",2-9-1996,2.0,2.0,4.0,70.0,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,r33RG06 - RG Solanum dulcamara-Phragmites aust...,0.1,4.962352,53.262944,100,Adviesburos (1)

In [5]:
pd.set_option('display.max_columns', None)
species.head(n=20)

,PlotObservationID,Species name,Layer,Cover %,Cover code,Taxon ID
0,192,Bolboschoenus maritimus s.s,0,2.0,+,13913
1,192,Phragmites australis,0,68.0,4,13078
2,192,Solanum dulcamara,0,2.0,+,13358
3,196,Agrostis stolonifera,0,2.0,+,12186
4,196,Calamagrostis canescens,0,2.0,+,12340
5,196,Epilobium hirsutum,0,18.0,2b,12611
6,196,Lycopus europaeus,0,2.0,+,12929
7,196,Phragmites australis,0,68.0,4,13078
8,196,Potentilla anserina,0,1.0,r,13151
9,196,Rubus species,0,1.0,r,17011
10,196,Salix repens,0,1.0,r,13264
11,233,Atriplex prostrata,0,1.0,r,12288
12,233,Bolboschoenus maritimus s.s,0,38.0,3,13913
13,233,Phragmites australis,0,68.0,4,13078
14,580,Calamagrostis canescens,0,3.0,1,12340
15,580,Cardamine pratensis,0,2.0,+,12372
16,580,Carex acuta,0,8.0,2a,12378
17,580,Carex acutiformis,0,2.0,+,12379
18,580,Convolvulus sepium,0,3.0,1,12355
19,580,Galium aparine,0,2.0,+,12702